"""Bounds and definitions for historical observations."""

DEFAULT_RECOVERY = 120
DEFAULT_TOLERANCE = 0.3
MAX_GAP_SECONDS = 1800
TARGET_HOLD_SECONDS = 300
MIN_MATCHES = 5
MIN_MATCH_DAYS = 3
MIN_COVERAGE = 80
SAMPLE_SECONDS = 300
MAX_POINTS = 50000
MAX_ADJUSTMENTS = 1000
SCHEMA_VERSION = 1
SEMANTICS_VERSION = 1
